name: build and flash  

# taking input from end user like Target your hardware(choise all the ) repo path

on:
  workflow_dispatch:
    inputs:
      open_BMC_repo_url:
        description: open_BMC_repo_url
        required: yes
        default: "git@github.com:openbmc/openbmc.git"
        type: string
      Target_your_hardware:
        description: Target your hardware
        required: yes
        default: "rl300-g11"
        type: choice
        options: 
          - rl300-g11
          - palmetto
          - zaius
          - dl360poc
          - p10bmc


    # outputs:
    #   some_output:
    #     description: "The second job output"
    #     value: ${{ jobs.my_job.outputs.job_output2 }}
        # description: some output
  # push:
  #    branches:
  #      - main

jobs:
  
  generate-build:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout the code"
        uses: actions/checkout@v3
      - name: clone the repo
        run: |
          whoami
          git clone git@github.com:openbmc/openbmc.git
          cd openbmc 

        shell: bash
      - name: Building for ${{inputs.Target_your_hardware}}
        run: |
          . setup zaius
          bitbake obmc-phosphor-image

        shell: bash
  # flash-fw:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     # required for accessing files in repository.
  #   - name: flash
  #       run: echo "flash"

   

# # Prerequisite
# # Ubuntu 14.04
# sudo apt-get install -y git build-essential libsdl1.2-dev texinfo gawk chrpath diffstat

# #  Download the source

# git clone git@github.com:openbmc/openbmc.git
# cd openbmc

# # Target your hardware
# # . setup <machine> [build_dir]

# # . ./setup rl300-g11
# . setup rl300-g11 build

# # build 
# bitbake obmc-phosphor-image




















#!/bin/bash
# #set proxies and env variables

# first step


# echo export GOROOT=/usr/local/go >> ~/.profile
# echo export GOPATH=\$HOME/go >> ~/.profile
# echo export PATH=\$GOPATH/bin:\$GOROOT/bin:\$PATH >> ~/.profile
# source ~/.profile



#git has been installed, set proxy information. 
# git config --global https.proxy http://web-proxy.houston.hpecorp.net:8080
# git config --global http.proxy http://web-proxy.houston.hpecorp.net:8080
#force git to use https
# git config --global url."https://github".insteadOf git://github


# 

# Once you get logged in run that in a shell script
# Then put your github key into your home .ssh directory
# Then do chmod 600 yourgithubkey.pem
# Then run git clone -b dev-gxp-gen11 git@github.hpe.com:hpe-iop/openbmc.git
# That should copy down the source tree







# /home/jamil/openbmc/meta-hpe/meta-gxp/recipes-bsp/image/files/
# Once you have cloned the repo copy those two files into that path
# cd /home/jamil/openbmc
# . ./setup rl300-g11
# bitbake obmc-phosphor-image
# That will kick off a build
