name: Go

on:
  push:
  workflow_dispatch:
jobs:
      
  reading_from_json_file:
    runs-on: ubuntu-latest
    outputs:
      output1: $ {{ steps.download_step.outputs.matrix }}
      output2: $ {{ steps.download_step.outputs.value }}
      output3: $ {{ steps.download_step.outputs.NEW_IP }}
      
    steps:
    - uses: actions/checkout@v3
    - name: download file

      id: download_step
      run: |
        NEW_IP_VALUE='10.14.77.203'
        echo "::set-output name=NEW_IP::$NEW_IP_VALUE" 

    
    
    - run: |
        echo ${{ steps.download_step.outputs.NEW_IP }}
    
    # - run: |
    #     echo "${{steps.download_step.outputs.matrix }}"
    

      shell: bash    
    
  execute_multiple_test:
    strategy:
      matrix:
        include:
        - BMC_IP: ${{ needs.reading_from_json_file.outputs.output3 }} 
        - BMC_IP: ${{ needs.reading_from_json_file.outputs.output3 }} 
        - BMC_IP: "10.14.77.205" 
        # ${{fromJson(needs.reading_from_json_file.outputs.output1)}} 
        
        
    runs-on: ubuntu-latest
    needs: reading_from_json_file
    
    steps:
    - uses: actions/checkout@v3    
          
    - name: Execute Toggle IPMI
      run: | 
        echo ${{ matrix.BMC_IP }}
        echo ${{ needs.reading_from_json_file.outputs.output1 }}
        # cd $GITHUB_WORKSPACE/automation
        # pwd
        # go run $GITHUB_WORKSPACE/automation/toggle_ipmi_service.go ${{ matrix.BMC_IP }}
  
      shell: bash 
