name: minio-
on:
  schedule: 
    - cron: '*/10 * * * *'
  
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        # with:
        #   ref: testing-scheduler


 
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: min_io_workflow
      run: |
        cd $GITHUB_WORKSPACE
        pwd

        go run min_io_workflow/send_a_request.go 

    # - name: Test
    #   run: go test -v ./math/

      shell: bash 

 


    # - name: Set bash working dir
    #   run: |
    #    echo "jamil"
