name: minio
on:
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set bash 
    - uses: actions/checkout@v3    
    - name: Set Go environment 
      run: |
        echo "jamil"

      shell: bash 
