name: minio-
on:
  # workflow_run:
  #   workflows: ["Run Tests"]
  #   branches: [main]
  #   types: 
  #     - completed
  schedule: 
    - cron: '*/10 * * * *'
  
  workflow_dispatch:
jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout the code"
        uses: actions/checkout@v3
        ref: 'ref-branch'
 
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
    
      - name: min_io_workflow
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          echo "hello world"
          go run min_io_workflow/ref_branch_file.go 
    
        shell: bash 

 
